db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts:
    - localhost
    - 127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 2
      timeout: 2
logging:
  level:
    root: INFO
    org.example.database.pool: INFO
    org:
      springframework.jdbc.core: TRACE
      hibernate:
        SQL: TRACE
        type.descriptor.sql.BasicBinder: TRACE
  file:
    name: dmdev.log
    path: /

spring:
  mvc:
    format:
      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show-sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
